version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "4001:3000"
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_URL=http://user-authentication:3004
      - PREFERENCES_SERVICE_URL=http://user-preferences:3001
      - FEED_SERVICE_URL=http://content-feed:3002
      - RECOMMENDATION_SERVICE_URL=http://content-recommendation:3003
      - CATEGORIES_SERVICE_URL=http://content-categories:3005
    depends_on:
      - user-authentication
      - user-preferences
      - content-feed
      - content-recommendation
      - content-categories

  # User Preferences Service
  user-preferences:
    build: ./user-preferences
    ports:
      - "4002:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=mongodb://admin:password@host.docker.internal:27019/user-preferences?authSource=admin

  # Content Feed Service
  content-feed:
    build: ./content-feed
    ports:
      - "4003:3002"
    depends_on:
      - redis
    environment:
      - NODE_ENV=development
      - PORT=3002
      - PREFERENCES_SERVICE_URL=http://user-preferences:3001
      - CATEGORIES_SERVICE_URL=http://content-categories:3005
      - RECOMMENDATION_SERVICE_URL=http://content-recommendation:3003
      - GNEWS_API_KEY=cb246a4da7dc041b6020dd5f7a16db88
      - AFRICA_NEWS_API_KEY=ae0ec8709fc34dd0b5efeb425aef953e
      - NEWSDATA_API_KEY=pub_7e8b81c719e34a3ea5d45ecef8cc702a
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379

  # Content Recommendation Service
  content-recommendation:
    build: ./content-recommendation
    ports:
      - "4004:3003"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - PREFERENCES_SERVICE_URL=http://user-preferences:3001
      - DATABASE_URL=mongodb://admin:password@host.docker.internal:27019/recommendations?authSource=admin

  # User Authentication Service
  user-authentication:
    build: ./user-authentication
    ports:
      - "4005:3004"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=development
      - PORT=3004
      - JWT_SECRET=your-secret-key
      - DATABASE_URL=mongodb://admin:password@host.docker.internal:27019/auth?authSource=admin
      - GOOGLE_CLIENT_ID=442434439258-aptdg2rnmis2cqqd64p4kqn2nd8qrc2l.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - FRONTEND_URL=http://localhost:4002
      - AUTH_SERVICE_URL=http://localhost:4005

  # Content Categories Service
  content-categories:
    build: ./content-categories
    ports:
      - "4006:3005"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=development
      - PORT=3005
      - DATABASE_URL=mongodb://admin:password@host.docker.internal:27019/categories?authSource=admin

  # Redis for Caching
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
